// Cost. Power Level boost percentage. Hull Boost. Shield Armor boost.
export const addons = {
    'None': { cost: 0, powerLevelBoost: 0, hullPointsBoost: 0, shieldArmorPointsBoost: 0},
    'Advanced Shields': { cost: 1, powerLevelBoost: 1, hullPointsBoost: 20, shieldArmorPointsBoost: 200 },
    'Heavy Armor': { cost: 1, powerLevelBoost: 1, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'High Speed': { cost: 1.5, powerLevelBoost: 1.5, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Tractor Beam': { cost: 1, powerLevelBoost: 1, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Ion Bombs': { cost: 1.3, powerLevelBoost: 1.3, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Ion Torpedoes': { cost: 1.4, powerLevelBoost: 1.4, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Massive Hangers 3+': { cost: 1, powerLevelBoost: 1, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Interdiction Generator 6+': { cost: 2.5, powerLevelBoost: 2.5, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Recon array': { cost: 1, powerLevelBoost: 1, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Transport': { cost: 1, powerLevelBoost: 1, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Advanced Computers': { cost: 1.1, powerLevelBoost: 1.1, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Hyperdrive': { cost: 1, powerLevelBoost: 1, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Flagship': { cost: 5, powerLevelBoost: 5, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'BOMB SHIP': { cost: 2, powerLevelBoost: 2, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Comms Jammer': { cost: 2.5, powerLevelBoost: 2.5, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Grabbing Claws': { cost: 1, powerLevelBoost: 1, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Ramming Hull 4+': { cost: 1, powerLevelBoost: 1, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Stealth Field': { cost: 4, powerLevelBoost: 4, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Minelayers 4+': { cost: 1, powerLevelBoost: 1, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Long Range Torpedoes': { cost: 1.2, powerLevelBoost: 1.2, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Flack Cannons 4+': { cost: 1.5, powerLevelBoost: 1.5, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Large Caliber Cannons 4+': { cost: 1.5, powerLevelBoost: 1.5, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Ground Bombardment Cannons 3+': { cost: 1.2, powerLevelBoost: 1.2, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Unguided Bombs': { cost: 1, powerLevelBoost: 1, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Guided Bombs': { cost: 1.5, powerLevelBoost: 1.5, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Cluster Bombs': { cost: 1.2, powerLevelBoost: 1.2, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Amphibious': { cost: 1.1, powerLevelBoost: 1.1, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Concussion Missiles': { cost: 1.2, powerLevelBoost: 1.2, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Proton Torpedos': { cost: 1.2, powerLevelBoost: 1.2, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Ion Cannons': { cost: 1.3, powerLevelBoost: 1.3, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Beam Cannons': { cost: 1.2, powerLevelBoost: 1.2, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'MINE, Explosive': { cost: 1, powerLevelBoost: 1, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'MINE, EMP': { cost: 1.1, powerLevelBoost: 1.1, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'MINE, Anti-Shields': { cost: 1, powerLevelBoost: 1, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Independent Weapons Generator': { cost: 1.2, powerLevelBoost: 1.2, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Skylance Launcher': { cost: 3, powerLevelBoost: 3, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Massive Scale': { cost: 2, powerLevelBoost: 2, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Electro Cannon': { cost: 2, powerLevelBoost: 2, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Ship Upgrade Part': { cost: 1, powerLevelBoost: 1, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Ship Part': { cost: 1, powerLevelBoost: 1, hullPointsBoost: 0, shieldArmorPointsBoost: 0 },
    'Civilian Vessel': { cost: 0.5, powerLevelBoost: 0.5, hullPointsBoost: 0, shieldArmorPointsBoost: 0 }
};

export const primaryArm = {
    'Laser Cannons': { cost: 1, powerLevelBoost: 1, lightAttack: 5, mediumAttack: 5, heavyAttack: 5 },
    'Proton Torpedoes': { cost: 1, powerLevelBoost: 1, lightAttack: 5, mediumAttack: 5, heavyAttack: 5 },
    'Ion Cannons': { cost: 1, powerLevelBoost: 1, lightAttack: 5, mediumAttack: 5, heavyAttack: 5 },
    'Concussion Missiles': { cost: 1, powerLevelBoost: 1, lightAttack: 5, mediumAttack: 5, heavyAttack: 5 },
    // Add more weapons as needed
};
